# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# use macports' GNU coreutils instead of BSD on Mac OS.
# use icecream's gcc and g++
export PATH=/opt/local/libexec/gnubin/:/usr/lib/icecream/bin:$PATH

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# Alias definitions.

# Check if bash_aliases is present and include it if possible
test -s ~/.bash_aliases && . ~/.bash_aliases || true

# Check if bash_functions is present and include it if possible
test -s ~/.bash_functions && . ~/.bash_functions || true

# enable color support of ls and also add handy aliases
if which dircolors &> /dev/null; then
    if [ "$TERM" != "dumb" ]; then
        eval "`dircolors -b`"
        alias ls='ls --color=auto'
    fi
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
test -s /etc/bash_completion &&  . /etc/bash_completion || true
# bash completion on ArchLinux
test -s /usr/share/git/completion/git-prompt.sh && . /usr/share/git/completion/git-prompt.sh || true
test -s /usr/share/git/completion/git-completion.bash && . /usr/share/git/completion/git-completion.bash || true
# bash completion on Mac OS
test -s /opt/local/etc/bash_completion && . /opt/local/etc/bash_completion || true

#I want a huge history!
export HISTFILESIZE=1000000
export HISTSIZE=1000000
export HISTCONTROL=ignoredups,erasedups,ignoreboth
export HISTIGNORE=ls,fg,bg

#my installs
export PATH=$PATH:/home/anselmo/bin:/home/anselmo/local/bin:/usr/local/bin:$HOME/projects/git-achievements/:$HOME/local/arcanist/arcanist/bin

export EDITOR="emacs -nw"
export LESS="-I -M -R"
shopt -s histappend

# Show current branch in directories under git version control
if [[ ${EUID} == 0 ]] ; then
    PS1='\[\033[01;31m\]\h\[\033[01;34m\] \W $(declare -F __git_ps1 &> /dev/null && __git_ps1 "(%s)")\$\[\033[00m\] '
else
    PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w $(declare -F __git_ps1 &> /dev/null && __git_ps1 "(%s)")\$\[\033[00m\] '
fi

# makes the prompt show the current state of the git workdir
#export GIT_PS1_SHOWDIRTYSTATE=true
#export GIT_PS1_SHOWUNTRACKEDFILES=true

# MacPorts Installer addition on 2012-04-16_at_11:14:18: adding an appropriate PATH variable for use with MacPorts.
export PATH=/usr/local/git/bin:/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.
