#!/bin/sh

cp_p()
{
   strace -q -ewrite cp -ax -- "${1}" "${2}" 2>&1 \
      | awk '{
        count += $NF
            if (count % 10 == 0) {
               percent = count / total_size * 100
               printf "%3d%% [", percent
               for (i=0;i<=percent;i++)
                  printf "="
               printf ">"
               for (i=percent;i<100;i++)
                  printf " "
               printf "]\r"
            }
         }
         END { print "" }' total_size=$(stat -c '%s' "${1}") count=0
}

svn_cleanall()
{
    svn st | awk '{print $2}' | xargs rm -rf
}

git_cleanall()
{
    git clean -xf | awk '{print $3}' | xargs rm -rf
}

git_update_dirs()
{
for x in `ls -d *.git`
do
    echo '======================================================'
    echo -n $x': '
    cd $x && git pull && cd ..
    echo '======================================================'
done
}

git_pruneall()
{
    for x in `git branch -a | grep remotes | cut -f 2 -d '/' | uniq`; do git remote prune $x; done
}


qtenv()
{
    BUILD=$1
    if [ $# -eq 0 ]; then
        echo "You must inform the build name!"
    elif [ $BUILD == "sdk" ]; then
	echo "Using QtSDK version"
        export LD_LIBRARY_PATH=$HOME/local/QtSDK/Desktop/Qt/474/gcc/lib:$LD_LIBRARY_PATH
        export LIBRARY_PATH=$HOME/local/QtSDK/Desktop/Qt/474/gcc/lib:$LIBRARY_PATH
        export PATH=$HOME/local/QtSDK/Desktop/Qt/474/gcc/bin:$PATH
    else
	echo "Using Qt" + $BUILD
        export LD_LIBRARY_PATH=$HOME/projects/Qt/build/$BUILD/lib:$LD_LIBRARY_PATH
        export LIBRARY_PATH=$HOME/projects/Qt/build/$BUILD/lib:$LIBRARY_PATH
        export PATH=$HOME/projects/Qt/build/$BUILD/bin:$PATH
    fi
}

rename_without_spaces()
{
	for i in *; do j=`echo $i | tr ' ' _`; mv "$i" $j; done;
}

