# for security reasons
alias rm='rm -i'
alias mv='mv -i'

# simplifying common commands
alias gvim='gvim -p'
alias v='vim'
alias ll='ls -lh'
alias nw='emacs -nw'

# boring typo
alias sl='ls'

# recursive grep in emacs is rgrep ;)
alias rgrep='grep -R'

# using colors!
alias grep='grep --colour=auto --exclude=*.svn-base'
alias vless='vim -u /usr/share/vim/vim71/macros/less.vim'

# I always forget 'time' when I wanna measure build time..
alias make='time make'

# archlinux: always use yaourt
alias pacman='yaourt'

# git achievements
alias git="git-achievements"
