# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
# ... and ignore same sucessive entries.
export HISTCONTROL=ignoreboth

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# Alias definitions.

# Check if bash_aliases is present and include it if possible
test -s ~/.bash_aliases && . ~/.bash_aliases || true

# Check if bash_functions is present and include it if possible
test -s ~/.bash_functions && . ~/.bash_functions || true

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
test -s /etc/bash_completion &&  . /etc/bash_completion || true

#I want a huge history!
export HISTFILESIZE=1000000
export HISTSIZE=1000000
export HISTCONTROL=ignoredups,erasedups,ignoreboth
export HISTIGNORE=ls,fg,bg

#my installs
export PATH=$PATH:/home/anselmo/bin:/home/anselmo/local/bin:/usr/local/bin

export EDITOR=vim
export LESS="-I -M -R"
shopt -s histappend
source /etc/bash_completion.d/git.sh
[[ -f /etc/profile.d/bash-completion.sh ]] && source /etc/profile.d/bash-completion.sh

# Show current branch in directories under git version control
if [[ ${EUID} == 0 ]] ; then
    PS1='\[\033[01;31m\]\h\[\033[01;34m\] \W $(__git_ps1 "(%s)")\$\[\033[00m\] '
else
    PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w $(__git_ps1 "(%s)")\$\[\033[00m\] '
fi
